# Generated by Django 4.2.23 on 2025-09-09 00:53

from django.db import migrations

from notifications.constants import NotificationTypes


class Migration(migrations.Migration):

    def create_notification_types(apps, schema_editor):
        NotificationType = apps.get_model("notifications", "NotificationType")
        for nt in NotificationTypes:
            NotificationType.objects.get_or_create(name=nt.value)

    def delete_notification_types(apps, schema_editor):
        NotificationType = apps.get_model("notifications", "NotificationType")
        for nt in NotificationTypes:
            NotificationType.objects.filter(name=nt.value).delete()

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_notification_types, delete_notification_types),
    ]
