# Generated by Django 4.2.23 on 2025-09-09 00:54

from django.db import migrations, models

from config import settings


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_populate_notification_types'),
    ]

    operations = [
            migrations.CreateModel(
                name='Device',
                fields=[
                    ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                    ('expo_push_token', models.CharField(max_length=255)),
                    ('created_at', models.DateTimeField(auto_now_add=True)),
                    ('user', models.ForeignKey(on_delete=models.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
                ],
            ),
        ]
