# Generated by Django 4.2.23 on 2025-10-25 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_utils', '0002_initial'),
        ('notifications', '0003_create_device_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_type_image', to='media_utils.image'),
        ),
    ]
