# Generated by Django 4.2.23 on 2025-08-16 13:50

from django.db import migrations

from eventos.constants import CategoryEnum, EventStates

def populate_event_states_and_categories(apps, schema_editor):
    EventState = apps.get_model('eventos', 'EventState')
    Category = apps.get_model('eventos', 'Category')

    for state in EventStates:
        EventState.objects.get_or_create(name=state.value)

    for category in CategoryEnum:
        Category.objects.get_or_create(name=category.value)

class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_initial'),
    ]

    operations = [
        migrations.RunPython(populate_event_states_and_categories),
    ]


