# Generated by Django 4.2.23 on 2025-08-25 21:14

from django.db import migrations

from eventos.constants import EventStates


class Migration(migrations.Migration):

    def populate_event_states(apps, schema_editor):
        EventState = apps.get_model('eventos', 'EventState')

        for state in EventStates:
            EventState.objects.get_or_create(name=state.value)


    dependencies = [
        ('eventos', '0003_populate_enums'),
    ]

    operations = [
        migrations.RunPython(populate_event_states),
    ]