# Generated by Django 4.2.23 on 2025-09-14 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media_utils", "0002_initial"),
        ("eventos", "0004_add_deleted_event_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_image",
                to="media_utils.image",
            ),
        ),
    ]
