# Generated by Django 4.2.23 on 2025-07-21 19:41

from django.db import migrations

def populate_job_types(apps, schema_editor):
    JobType = apps.get_model('eventos', 'JobType')
    job_types = [
        
    ]
    
    for job_type in job_types:
        JobType.objects.get_or_create(name=job_type)

class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_event_category_alter_event_description_and_more'),
    ]

    operations = [populate_job_types(migrations.RunPython(populate_job_types))
    ]
