# Generated by Django 4.2.23 on 2025-09-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='stream_announcements_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='stream_workers_channel_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
