# Generated by Django 4.2.23 on 2025-07-21 20:18

from django.db import migrations

def populate_categories(apps, schema_editor):
    Category = apps.get_model('eventos', 'Category')
    categories = [
        "Concierto",
        "Festival",
        "Casamiento",
        "Evento corporativo",
        "Feria",
        "Desfile",
        "Evento deportivo",
        "Otros"
    ]

    for name in categories:
        Category.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_populate_jobtypes'),
    ]

    operations = [
        migrations.RunPython(populate_categories)
    ]
