# Generated by Django 4.2.23 on 2025-07-21 20:25

from django.db import migrations

def add_more_categories(apps, schema_editor):
    JobType = apps.get_model('eventos', 'JobType')
    new_job_types = [
        "Otro"
    ]

    for job_type in new_job_types:
        JobType.objects.get_or_create(name=job_type)

class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_populate_category_events'),
    ]

    operations = [
        migrations.RunPython(add_more_categories)
    ]
