# Generated by Django 4.2.23 on 2025-07-21 20:43

from django.db import migrations

def populate_states(apps, schema_editor):
    EventState = apps.get_model('eventos', 'EventState')

    event_states = [
        "Borrador",
        "Publicado",
        "En curso",
        "Finalizado",
        "Cancelado"
    ]

    for name in event_states:
        EventState.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_add_states'),
    ]

    operations = [
    ]
