# Generated by Django 4.2.23 on 2025-07-21 20:56

from django.db import migrations

def populate_states(apps, schema_editor):
    VacancyState = apps.get_model('eventos', 'VacancyState')

    vacancy_states = [
        "Pendiente",
        "Publicada",
        "Cubierta",
        "Cancelada"
    ]

    for name in vacancy_states:
        VacancyState.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_vacancystate_vacancy_shift_requirements'),
    ]

    operations = [
        migrations.RunPython(populate_states)
    ]
