# Generated by Django 4.2.23 on 2025-07-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_add_vacancy_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
