# Generated by Django 4.2.23 on 2025-07-22 12:44

from django.db import migrations

def delete_vacancy_states(apps, schema_editor):
    VacancyState = apps.get_model('eventos', 'VacancyState')
    VacancyState.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_alter_vacancy_description'),
    ]

    operations = [
        migrations.RunPython(delete_vacancy_states),
    ]
