# Generated by Django 4.2.23 on 2025-07-22 12:45

from django.db import migrations

def create_correct_vacancy_states(apps, schema_editor):
    VacancyState = apps.get_model('eventos', 'VacancyState')

    correct_states = [
        "En Borrador",
        "Activa",
        "Oculta",
        "Llena",
        "Vencida"
    ]

    for name in correct_states:
        VacancyState.objects.get_or_create(name=name)

class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0015_delete_vacancy_states'),
    ]

    operations = [
        migrations.RunPython(create_correct_vacancy_states),
    ]
