# Generated by Django 4.2.23 on 2025-07-26 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0018_alter_event_latitude_alter_event_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='specific_job_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
