# Generated by Django 4.2.23 on 2025-08-01 16:41

from django.db import migrations


class Migration(migrations.Migration):
    def add_deleted_state(apps, schema_editor):
        VacancyState = apps.get_model('eventos', 'VacancyState')
        VacancyState.objects.create(name='Eliminada')

    dependencies = [
        ('eventos', '0020_application'),
    ]

    operations = [
        migrations.RunPython(add_deleted_state),
    ]
