# Generated by Django 4.2.23 on 2025-07-07 21:40

from django.db import migrations

def create_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.create(name='admin')
    Group.objects.create(name='empleado')
    Group.objects.create(name='empleador')
    
def delete_roles(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['admin', 'empleado', 'empleador']).delete()

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_roles, reverse_code=delete_roles)
    ]
