# Generated by Django 4.2.23 on 2025-07-13 17:54

from django.db import migrations

def rename_groups_forward(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    try:
        empleado = Group.objects.get(name='empleado')
        empleado.name = 'employee'
        empleado.save()
    except Group.DoesNotExist:
        pass

    try:
        empleador = Group.objects.get(name='empleador')
        empleador.name = 'employer'
        empleador.save()
    except Group.DoesNotExist:
        pass

def rename_groups_backward(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    try:
        employee = Group.objects.get(name='employee')
        employee.name = 'empleado'
        employee.save()
    except Group.DoesNotExist:
        pass

    try:
        employer = Group.objects.get(name='employer')
        employer.name = 'empleador'
        employer.save()
    except Group.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_create_user_roles'),
    ]

    operations = [migrations.RunPython(rename_groups_forward, rename_groups_backward)
    ]
