# Generated by Django 4.2.23 on 2025-07-13 19:01

from django.db import migrations
def create_or_rename_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    # Intentamos renombrar grupo 'empleado' a 'employee'
    try:
        empleado_group = Group.objects.get(name='empleado')
        empleado_group.name = 'employee'
        empleado_group.save()
    except Group.DoesNotExist:
        # Si no existe 'empleado', creamos 'employee' si no existe
        Group.objects.get_or_create(name='employee')

    # Intentamos renombrar grupo 'empleador' a 'employer'
    try:
        empleador_group = Group.objects.get(name='empleador')
        empleador_group.name = 'employer'
        empleador_group.save()
    except Group.DoesNotExist:
        # Si no existe 'empleador', creamos 'employer' si no existe
        Group.objects.get_or_create(name='employer')

def reverse_func(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    # Revertimos los nombres a los originales (opcional)
    try:
        employee_group = Group.objects.get(name='employee')
        employee_group.name = 'empleado'
        employee_group.save()
    except Group.DoesNotExist:
        pass

    try:
        employer_group = Group.objects.get(name='employer')
        employer_group.name = 'empleador'
        employer_group.save()
    except Group.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_or_rename_groups, reverse_func),
    ]
