# Generated by Django 4.2.23 on 2025-09-25 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MercadoPagoAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mp_user_id", models.CharField(max_length=100, unique=True)),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                ("public_key", models.CharField(blank=True, max_length=200, null=True)),
                ("live_mode", models.BooleanField(default=False)),
                ("expires_in", models.IntegerField(blank=True, null=True)),
                ("scope", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mercado_pago_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
