# Generated by Django 4.2.23 on 2025-10-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_auth", "0003_alter_customuser_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phoneverification",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
