# Generated by Django 4.2.23 on 2025-07-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_alter_event_category_alter_event_description_and_more'),
        ('user_auth', '0003_phoneverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='job_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees', to='eventos.jobtype'),
        ),
    ]
