# Generated by Django 4.2.23 on 2025-10-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_alter_phoneverification_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
