# Generated by Django 4.2.23 on 2025-07-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_customuser_profile_image_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
