# Generated by Django 4.2.23 on 2025-07-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_utils', '0001_initial'),
        ('user_auth', '0007_employeeprofile_latitude_employeeprofile_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile_image', to='media_utils.image'),
        ),
    ]
