# Generated by Django 4.2.23 on 2025-07-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_remove_customuser_profile_image_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='job_types',
            field=models.ManyToManyField(blank=True, related_name='employees', to='eventos.jobtype'),
        ),
    ]
