# Generated by Django 4.2.23 on 2025-10-01 18:50
from django.db import migrations

def populate_penalty_states(apps, schema_editor):
    from rating.constats import PenaltyStates

    StatePenalty = apps.get_model('rating', 'StatePenalty')
    for state in PenaltyStates:
        StatePenalty.objects.get_or_create(name=state.value)

class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),  # O la migración anterior a esta
    ]

    operations = [
        migrations.RunPython(populate_penalty_states),
    ]