# Generated by Django 4.2.23 on 2025-10-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_populate_penalty_states'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='average_rating',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
