# Generated by Django 4.2.23 on 2026-03-01 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0007_populate_penalty_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalty_state_changes', to=settings.AUTH_USER_MODEL)),
                ('penalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='rating.penalty')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='rating.statepenalty')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
