from enum import Enum


class NotificationTypes(str, Enum):
    OFFERT = "OFFERT"
    APPLICATION = "APPLICATION"
    VACANCY_CREATION = "VACANCY_CREATION"
    VACANCY_UPDATE = "VACANCY_UPDATE"
    SYSTEM = "SYSTEM"
    MESSAGE = "MESSAGE"
    REMINDER = "REMINDER"
    ALERT = "ALERT"
    EVENT_CREATION = "EVENT_CREATION"
    EVENT_UPDATE = "EVENT_UPDATE"
    JOBS = "JOBS"

