# Generated by Django 4.2.23 on 2025-08-16 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('user_auth', '0001_initial'),
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='user_auth.employeeprofile'),
        ),
        migrations.AddField(
            model_name='application',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='vacancies.shift'),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('employee', 'shift')},
        ),
    ]
