# Generated by Django 4.2.23 on 2025-08-17 17:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
        ('vacancies', '0002_populate_enums'),
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='applications.application')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='user_auth.employeeprofile')),
                ('employeer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='user_auth.employerprofile')),
                ('shifts', models.ManyToManyField(blank=True, related_name='offers', to='vacancies.shift')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
