# Generated by Django 4.2.23 on 2025-08-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='employeer',
            new_name='employer',
        ),
    ]
