# Generated by Django 4.2.23 on 2025-08-23 11:49

from django.db import migrations

def create_offer_states(apps, schema_editor):
    OfferState = apps.get_model('applications', 'OfferState')
    states = ["PENDING", "ACCEPTED", "REJECTED", "CANCELED", "EXPIRED"]
    for state in states:
        OfferState.objects.create(name=state)

class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_offerstate_offer"),
    ]

    operations = [
        migrations.RunPython(create_offer_states),
    ]
