# Generated by Django 4.2.23 on 2025-08-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_rename_employeer_offer_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Fecha límite para aceptar la oferta', null=True),
        ),
    ]
