# Generated by Django 4.2.23 on 2025-08-20 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_populate_enums'),
        ('applications', '0005_offer_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='shifts',
        ),
        migrations.AddField(
            model_name='offer',
            name='selected_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_offers', to='vacancies.shift'),
        ),
    ]
