# Generated by Django 4.2.23 on 2025-08-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_populate_enums'),
        ('applications', '0006_remove_offer_shifts_offer_selected_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='shifts',
            field=models.ManyToManyField(blank=True, related_name='offers', to='vacancies.shift'),
        ),
    ]
