# Generated by Django 4.2.23 on 2025-09-03 15:05

from django.db import migrations

def create_application_states(apps, schema_editor):
    ApplicationState = apps.get_model("applications", "ApplicationState")
    states = ["PENDING", "OFFERED", "CONFIRMED", "REJECTED", "CANCELED"]

    for state in states:
        ApplicationState.objects.create(name=state)

def delete_application_states(apps, schema_editor):
    ApplicationState = apps.get_model('applications', 'ApplicationState')
    ApplicationState.objects.filter(
        name__in=["PENDING", "OFFERED", "CONFIRMED", "REJECTED", "CANCELED"]
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_applicationstate_remove_application_status_and_more'),
    ]

    operations = [
        migrations.RunPython(create_application_states, delete_application_states)
    ]
