# Generated by Django 4.2.23 on 2025-09-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    def create_offer_jobs_states(apps, schema_editor):
        OfferState = apps.get_model('applications', 'OfferState')
        states = ["COMPLETED", "NOT_SHOWN"]
        for state in states:
            OfferState.objects.create(name=state)

    def delete_jobs_offer_states(apps, schema_editor):
        OfferState = apps.get_model('applications', 'OfferState')
        OfferState.objects.filter(
            name__in=["COMPLETED", "NOT_SHOWN"]
        ).delete()

    dependencies = [
        ('applications', '0007_add_application_states'),
    ]

    operations = [
        migrations.RunPython(create_offer_jobs_states, delete_jobs_offer_states),
    ]
