# Generated by Django 4.2.23 on 2025-08-21 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_populate_enums'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0007_offer_shifts'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('job_type', models.CharField(max_length=100)),
                ('fecha_turno', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('empresa', models.CharField(max_length=255)),
                ('vencimiento', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('additional_comments', models.TextField(blank=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='applications.offer')),
                ('requirements', models.ManyToManyField(blank=True, to='vacancies.requirements')),
            ],
        ),
    ]
