# Generated by Django 4.2.23 on 2025-08-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_offerconfirmation'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerconfirmation',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
