# Generated by Django 4.2.23 on 2025-10-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_auto_20251003_0930"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="mp_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
