# Generated by Django 4.2.23 on 2025-10-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_mp_payment_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mercadopagoaccount",
            name="mp_user_id",
            field=models.IntegerField(unique=True),
        ),
    ]
