# Generated by Django 4.2.23 on 2025-10-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_mercadopagoaccount_mp_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mercadopagoaccount",
            name="mp_user_id",
            field=models.BigIntegerField(unique=True),
        ),
    ]
