# Generated by Django 4.2.23 on 2025-08-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('public_id', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('profile', 'Profile Image'), ('event', 'Event Image'), ('other', 'Other')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
