# Generated by Django 4.2.23 on 2025-08-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_utils", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="public_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
