# Generated by Django 4.2.23 on 2025-08-16 13:54

from django.db import migrations

from vacancies.constants import JobTypesEnum, VacancyStates

def populate_vacancy_states_and_job_types(apps, schema_editor):
    VacancyState = apps.get_model('vacancies', 'VacancyState')
    JobType = apps.get_model('vacancies', 'JobType')

    for state in VacancyStates:
        VacancyState.objects.get_or_create(name=state.value)

    for job_type in JobTypesEnum:
        JobType.objects.get_or_create(name=job_type.value)

class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_vacancy_states_and_job_types),
    ]
