# Generated by Django 4.2.23 on 2025-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0002_populate_enums"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="qr_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
