# Generated by Django 4.2.23 on 2025-09-13 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vacancies", "0003_shift_qr_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shift",
            name="qr_enabled",
        ),
    ]
